version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /log-lottery
    schedule:
      interval: monthly
    open-pull-requests-limit: 5

  - package-ecosystem: cargo
    directory: /log-lottery/src-tauri
    schedule:
      interval: monthly
    open-pull-requests-limit: 5

  - package-ecosystem: cargo
    directory: /log-lottery/ws_server
    schedule:
      interval: monthly
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
